### ISSUE TITLE
spelling mistake in  property

### ISSUE THREAD

**Issue by chrillek** [kaplanrehab/Devonthink-3-Unofficial-API#1]
several of the  jxa  scripts contain "...length" instead of "...length". I don't have time to fix this, therefore the issue. Also, I suggest not saving those as "scpt" but rather as "js". In the current format, they can't be used with any code editor like coteditor or Coderunner or VS Code.

**Comment by richardkaplan** [comment]
Thanks - will let 8isnothing respond further - I believe these are inactive parts of the project just there for background purposes - I  agree it would be helpful to fix and/or clarify in either case.

**Comment by 8isnothing** [comment]
Hey @chrillek! Thanks for pointing those out. I've fixed the typos =).

Re saving the files as .js: it sounds awesome. I really rather code them in VS Code instead of Script Editor. I wonder, though, if there are any caveats for this approach? I remember reading/experimenting with this approach and encountering some bugs.

**Comment by chrillek** [comment]
Using is works just fine in my experience.

**Comment by 8isnothing** [comment]
Thanks! I’ll try this approach for this project!
